# Generated by Django 6.0.2 on 2026-03-25 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundView',
            fields=[
                ('ns_id', models.CharField(db_column='ns_id', help_text='NORMAN SLE identifier', max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', help_text='Compound name (COALESCE from multiple sources)', null=True)),
                ('smiles', models.TextField(blank=True, db_column='smiles', help_text='SMILES notation', null=True)),
                ('inchi', models.TextField(blank=True, db_column='inchi', help_text='InChI string', null=True)),
                ('inchikey', models.CharField(blank=True, db_column='inchikey', help_text='InChIKey (27 character hash)', max_length=27, null=True)),
                ('cas', models.CharField(blank=True, db_column='cas', help_text='CAS Registry Number', max_length=50, null=True)),
                ('dtxsid', models.CharField(blank=True, db_column='dtxsid', help_text='DSSTox Substance ID (CompTox)', max_length=100, null=True)),
                ('nsid', models.CharField(blank=True, db_column='nsid', help_text='NORMAN substance ID', max_length=100, null=True)),
                ('mass', models.CharField(blank=True, db_column='mass', help_text='Molecular mass (as text)', max_length=50, null=True)),
                ('xlogp', models.CharField(blank=True, db_column='xlogp', help_text='XLogP value (as text)', max_length=50, null=True)),
                ('dtx_id', models.IntegerField(blank=True, db_column='dtx_id', help_text='Internal DTX database ID', null=True)),
                ('pc_id', models.IntegerField(blank=True, db_column='pc_id', help_text='Internal PubChem database ID', null=True)),
                ('cid', models.BigIntegerField(blank=True, db_column='cid', help_text='PubChem Compound ID (CID)', null=True)),
                ('inchikey_smiles', models.CharField(blank=True, db_column='inchikey_smiles', help_text='InChIKey derived from SMILES', max_length=27, null=True)),
                ('inchikey_inchi', models.CharField(blank=True, db_column='inchikey_inchi', help_text='InChIKey derived from InChI', max_length=27, null=True)),
                ('pc_record_id', models.IntegerField(blank=True, db_column='pc_record_id', help_text='PubChem record ID', null=True)),
                ('compound_id', models.IntegerField(blank=True, db_column='compound_id', help_text='Internal compound ID', null=True)),
                ('list_count', models.BigIntegerField(blank=True, db_column='list_count', help_text='Number of lists containing this compound', null=True)),
                ('mass_num', models.FloatField(blank=True, db_column='mass_num', help_text='Molecular mass as numeric (converted from text)', null=True)),
                ('xlogp_num', models.FloatField(blank=True, db_column='xlogp_num', help_text='XLogP as numeric (converted from text)', null=True)),
                ('name_lc', models.TextField(blank=True, db_column='name_lc', help_text='Lowercase version of name for searching', null=True)),
                ('name_bucket', models.IntegerField(blank=True, db_column='name_bucket', help_text='Name categorization: 0=starts with letter, 1=starts with digit, 2=other', null=True)),
                ('name_is_clean', models.BooleanField(blank=True, db_column='name_is_clean', help_text='True if name contains only letters, spaces, and hyphens', null=True)),
                ('name_noise_len', models.IntegerField(blank=True, db_column='name_noise_len', help_text='Count of non-letter/space/hyphen characters in name', null=True)),
            ],
            options={
                'verbose_name': 'Chemical Compound',
                'verbose_name_plural': 'Chemical Compounds',
                'db_table': 'mv_compound_cards',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chatbot_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id', 'started_at'], name='chatbot_ses_session_c258c6_idx'), models.Index(fields=['is_active', 'last_activity'], name='chatbot_ses_is_acti_fc71b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_faq_button', models.BooleanField(default=False)),
                ('skip_tier', models.IntegerField(default=0)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('tier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('response_type', models.CharField(blank=True, max_length=50, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_type', models.CharField(choices=[('first_question', 'First Question'), ('faq_button', 'FAQ Button'), ('llm_router', 'LLM Router'), ('followup', 'Follow-up'), ('override', 'Database Override'), ('negative_feedback', 'Negative Feedback')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended_tier', models.IntegerField(blank=True, null=True)),
                ('is_followup', models.BooleanField(default=False)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('override_applied', models.BooleanField(default=False)),
                ('override_keywords', models.JSONField(blank=True, null=True)),
                ('history_length', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_routing_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('routing', 'Routing Decision'), ('tier_attempt', 'Tier Attempt'), ('followup', 'Follow-up Detection'), ('override', 'Database Override'), ('error', 'Error'), ('info', 'Information')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_system_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TierAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(0, 'Follow-up'), (1, 'FAQ'), (2, 'PDF RAG'), (3, 'SQL Agent'), (4, 'LLM Fallback')], db_index=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('success', 'Success'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('main_term', models.CharField(blank=True, max_length=255, null=True)),
                ('synonyms', models.JSONField(blank=True, null=True)),
                ('generation_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('execution_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_attempts', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_tier_attempts',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chatbot_mes_session_cc8550_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['tier', 'response_type'], name='chatbot_mes_tier_606586_idx'),
        ),
    ]
